[2024-06-17T13:28:54.645+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: insert_data_dag.create_random_table manual__2024-06-17T13:16:50.823568+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
